################### BATUMI RAPTOR COUNT #######################
######### Script sets for compiling count data ################
############ Converter for Trektellen to BRC format ###########
###############################################################
# before you run that script #######
# replace station names with numbers
# change date format to YYYY-MM-DD
# change time format to HH:MM:SS
### read data ###

setwd(workdir)
full_data<-read.csv("trektellen_data.csv", header=T, fileEncoding="UTF-8", sep="\t")

#! trektellen files are written in UTF-7
full_data<-data.frame(full_data)
######################## Converter START ########################
colnames(full_data)[colnames(full_data) == "migtype"]<-"health"
colnames(full_data)[colnames(full_data) == "plumage"]<-"morph"
colnames(full_data)[colnames(full_data) == "timestamp"]<-"time"
colnames(full_data)[colnames(full_data) == "telpost"]<-"station"
colnames(full_data)[colnames(full_data) == "speciesname"]<-"species"
colnames(full_data)[colnames(full_data) == "soortkey"]<-"species"
colnames(full_data)[colnames(full_data) == "count"]<-"number"
colnames(full_data)[colnames(full_data) == "countback"]<-"countsouth" # error!!!
colnames(full_data)[colnames(full_data) == "counttype"]<-"counttype"
colnames(full_data)[colnames(full_data) == "speciesid"]<-"speciesid"

full_data$species<-as.character(full_data$species)
full_data$age<-as.character(full_data$age)
full_data$morph<-as.character(full_data$morph)
full_data$health<-as.character(full_data$health)
full_data$counttype<-as.character(full_data$counttype)
full_data$sex<-as.character(full_data$sex)

#### set abbreviations straight ####
full_data$age[full_data$age == "A"]<-"ad"
full_data$age[full_data$age == "I"]<-"imm"
full_data$age[full_data$age == "J"]<-"juv"
full_data$age[full_data$age == "Non-Juv"]<-"nonjuv"
full_data$age[full_data$age == "non-juv"]<-"nonjuv"
full_data$morph[full_data$morph == "D"]<-"dark"
full_data$morph[full_data$morph == "L"]<-"light"
full_data$health[full_data$health == "I"]<-"inj"
full_data$health[full_data$health == "K"]<-"kil"
full_data$sex[full_data$sex == "FC"]<-"fc"
full_data$sex[full_data$sex == "M"]<-"m"
full_data$sex[full_data$sex == "F"]<-"f"
full_data$counttype[full_data$counttype == "S"]<-"SC"
full_data$counttype[full_data$counttype == "D"]<-"DC"
full_data$species[full_data$species == "Accspec"]<-"SparrowH/Goshawk"
full_data$species[full_data$species == "BK"]<-"BlackKite" 
full_data$species[full_data$species == "BlaKite"]<-"BlackKite"
full_data$species[full_data$species == "BK_JUV"]<-"BlackKite_JUV"
full_data$species[full_data$species == "BK_NONJUV"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "Bk_juv"]<-"BlackKite_JUV"
full_data$species[full_data$species == "Bk_imm"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "Bk_ad"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "BKjuv"]<-"BlackKite_JUV"
full_data$species[full_data$species == "BKimm"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "BKad"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "BK_Ad"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "BK_Non-juv"]<-"BlackKite_NONJUV"
full_data$species[full_data$species == "BK_Juv"]<-"BlackKite_JUV"
full_data$species[full_data$species == "BE"]<-"BootedE"
full_data$species[full_data$species == "BEL"]<-"BootedEL" 
full_data$species[full_data$species == "BED"]<-"BootedED" 
full_data$species[full_data$species == "Buzspec"]<-"Buzzard"
full_data$species[full_data$species == "Buzzard sp"]<-"Buzzard"
full_data$species[full_data$species == "Buz/HonBuz"]<-"Buzzard"
full_data$species[full_data$species == "Buz"]<-"Buzzard"
full_data$species[full_data$species == "BUZ"]<-"Buzzard"
full_data$species[full_data$species == "B"]<-"Buzzard"
full_data$species[full_data$species == "BlaStork"]<-"BlackStork"
full_data$species[full_data$species == "BS"]<-"BlackStork"
full_data$species[full_data$species == "BS/WS"]<-"Stork"
full_data$species[full_data$species == "BlackVulture"]<-"BlackV" 
full_data$species[full_data$species == "BV"]<-"BlackV"
full_data$species[full_data$species == "CommonB"]<-"CommonBuz"
full_data$species[full_data$species == "CB"]<-"CommonBuz" 
full_data$species[full_data$species == "Crane"]<-"CommonCrane" 
full_data$species[full_data$species == "CC"]<-"CommonCrane"
full_data$species[full_data$species == "CommonC"]<-"CommonCrane"
full_data$species[full_data$species == "ComCrane"]<-"CommonCrane"
full_data$species[full_data$species == "CommonK"]<-"CommonKestrel"
full_data$species[full_data$species == "CommonKes"]<-"CommonKestrel"
full_data$species[full_data$species == "CK"]<-"CommonKestrel"
full_data$species[full_data$species == "CLK"]<-"Kestrel-SPEC"
full_data$species[full_data$species == "Crested HB"]<-"CrestedHB"
full_data$species[full_data$species == "CHB"]<-"CrestedHB"
full_data$species[full_data$species == "Demoisellecrane"]<-"DemoiselleCrane"
full_data$species[full_data$species == "Demoiselle crane"]<-"DemoiselleCrane"
full_data$species[full_data$species == "DalmatianP"]<-"DalmatianPelican"
full_data$species[full_data$species == "EgytianV"]<-"EgyptianV"
full_data$species[full_data$species == "Egy"]<-"EgyptianV"
full_data$species[full_data$species == "SparrowH"]<-"EurasianSH"
full_data$species[full_data$species == "ESH"]<-"EurasianSH"
full_data$species[full_data$species == "ESPH"]<-"EurasianSH"
full_data$species[full_data$species == "Fal"]<-"Falcon-SPEC"
full_data$species[full_data$species == "GSE"]<-"GreaterSE"
full_data$species[full_data$species == "GE"]<-"GoldenE"
full_data$species[full_data$species == "Gh"]<-"Goshawk"
full_data$species[full_data$species == "GH"]<-"Goshawk"
full_data$species[full_data$species == "Griffon"]<-"GriffonV" 
full_data$species[full_data$species == "Griffon V"]<-"GriffonV" 
full_data$species[full_data$species == "GV"]<-"GriffonV" 
full_data$species[full_data$species == "Har"]<-"Harrier-SPEC"
full_data$species[full_data$species == "harrier sp"]<-"Harrier-SPEC"
full_data$species[full_data$species == "Harspec"]<-"Harrier-SPEC"
full_data$species[full_data$species == "Circus-SPEC"]<-"Harrier-SPEC"
full_data$species[full_data$species == "Hen H"]<-"Hen"
full_data$species[full_data$species == "HOb"]<-"Hobby"
full_data$species[full_data$species == "HOB"]<-"Hobby"
full_data$species[full_data$species == "Hob"]<-"Hobby"
full_data$species[full_data$species == "Hob/RFF"]<-"Hobby/RedFF"
full_data$species[full_data$species == "HobRFF"]<-"Hobby/RedFF"
full_data$species[full_data$species == "HB "]<-"HB"
full_data$species[full_data$species == "HBjuv"]<-"HB_JUV"
full_data$species[full_data$species == "HBad"]<-"HB_AD"
full_data$species[full_data$species == "HB_juv"]<-"HB_JUV"
full_data$species[full_data$species == "HB_ad"]<-"HB_AD"
full_data$species[full_data$species == "HB_Juv"]<-"HB_JUV"
full_data$species[full_data$species == "HB_Ad"]<-"HB_AD"
full_data$species[full_data$species == "Imp"]<-"ImperialE"
full_data$species[full_data$species == "ImpE"]<-"ImperialE"
full_data$species[full_data$species == "Imp E"]<-"ImperialE"
full_data$species[full_data$species == "LUID"]<-"LargeEAGLE"
full_data$species[full_data$species == "LAquila-SPEC"]<-"LargeEAGLE"
full_data$species[full_data$species == "Large EAGLE"]<-"LargeEAGLE"
full_data$species[full_data$species == "LEspec"]<-"LargeEAGLE"
full_data$species[full_data$species == "LesGreste"]<-"LargeEAGLE"
full_data$species[full_data$species == "LesGrSte"]<-"LargeEAGLE"
full_data$species[full_data$species == "LesGrestep"]<-"LargeEAGLE"
full_data$species[full_data$species == "LesGresteppe"]<-"LargeEAGLE"
full_data$species[full_data$species == "Large Eagle"]<-"LargeEAGLE"
full_data$species[full_data$species == "large FALCON"]<-"LargeFALCON"
full_data$species[full_data$species == "LargeFalcon"]<-"LargeFALCON"
full_data$species[full_data$species == "LFspec"]<-"LargeFALCON"
full_data$species[full_data$species == "Fspec"]<-"LargeFALCON"
full_data$species[full_data$species == "Lkes"]<-"LesserKestrel"
full_data$species[full_data$species == "LKes"]<-"LesserKestrel"
full_data$species[full_data$species == "Kestrel"]<-"CommonKestrel"
full_data$species[full_data$species == "Kes"]<-"CommonKestrel"
full_data$species[full_data$species == "Kest/LesKest"]<-"Kestrel-SPEC"
full_data$species[full_data$species == "Kesspec"]<-"Kestrel-SPEC"
full_data$species[full_data$species == "LK"]<-"LesserKestrel"
full_data$species[full_data$species == "LesserKes"]<-"LesserKestrel"
full_data$species[full_data$species == "LesKes"]<-"LesserKestrel"
full_data$species[full_data$species == "LSE"]<-"LesserSE"
full_data$species[full_data$species == "LSH"]<-"LevantSH"
full_data$species[full_data$species == "LSPH"]<-"LevantSH"
full_data$species[full_data$species == "LevantS"]<-"LevantSH"
full_data$species[full_data$species == "LLB"]<-"LongLB"
full_data$species[full_data$species == "Long-legged buzzard"]<-"LongLB"
full_data$species[full_data$species == "MAR"]<-"Mar"
full_data$species[full_data$species == "Mer"]<-"Merlin"
full_data$species[full_data$species == "MUID"]<-"MediumRaptor"
full_data$species[full_data$species == "Monpal"]<-"MonPalHen"
full_data$species[full_data$species == "MonPal"]<-"MonPalHen"
full_data$species[full_data$species == "MonpalHen"]<-"MonPalHen"
full_data$species[full_data$species == "OSP"]<-"Osprey"
full_data$species[full_data$species == "Osp"]<-"Osprey" 
full_data$species[full_data$species == "Per"]<-"Peregrine" 
full_data$species[full_data$species == "Peregrine/Saker"]<-"LargeFALCON"
full_data$species[full_data$species == "PerSak"]<-"LargeFALCON"
full_data$species[full_data$species == "PerSakLan"]<-"LargeFALCON"
full_data$species[full_data$species == "RFF"]<-"RedFF"
full_data$species[full_data$species == "RK"]<-"RedKite"
full_data$species[full_data$species == "Rol"]<-"Roller"
full_data$species[full_data$species == "RLB"]<-"RoughLB"
full_data$species[full_data$species == "SakerF"]<-"Saker" 
full_data$species[full_data$species == "Sak"]<-"Saker" 
full_data$species[full_data$species == "SB"]<-"StepBuz"
full_data$species[full_data$species == "SteppeB"]<-"StepBuz"
full_data$species[full_data$species == "SBHB"]<-"Buzzard"
full_data$species[full_data$species == "SH"]<-"SparrowH-SPEC"
full_data$species[full_data$species == "LevantS/Sparrow"]<-"SparrowH-SPEC"
full_data$species[full_data$species == "Shspec"]<-"SparrowH-SPEC"
full_data$species[full_data$species == "SPH"]<-"SparrowH-SPEC"
full_data$species[full_data$species == "SPH/GH"]<-"SparrowH/Goshawk"
full_data$species[full_data$species == "SPGH"]<-"SparrowH/Goshawk"
full_data$species[full_data$species == "STE"]<-"ShortTE"
full_data$species[full_data$species == "SHTE"]<-"ShortTE"
full_data$species[full_data$species == "Seowl"]<-"ShortEaredOwl" 
full_data$species[full_data$species == "SEowl"]<-"ShortEaredOwl" 
full_data$species[full_data$species == "Short-earedOwl"]<-"ShortEaredOwl"
full_data$species[full_data$species == "ShortEO"]<-"ShortEaredOwl" 
full_data$species[full_data$species == "SEO"]<-"ShortEaredOwl"
full_data$species[full_data$species == "STEP"]<-"SteppeE"
full_data$species[full_data$species == "SUID"]<-"MediumRaptor" # only very little numbers
full_data$species[full_data$species == "TurtleDove"]<-"TurtleD"
full_data$species[full_data$species == "UID"]<-"MediumRaptor" # only very little numbers
full_data$species[full_data$species == "WTE"]<-"WhiteTE" 
full_data$species[full_data$species == "Wh-TailE"]<-"WhiteTE" 
full_data$species[full_data$species == "White-tailedE"]<-"WhiteTE" 
full_data$species[full_data$species == "White-TE"]<-"WhiteTE" 
full_data$species[full_data$species == "Wh-Tail E"]<-"WhiteTE"
full_data$species[full_data$species == "WhiStork"]<-"WhiteStork"
full_data$species[full_data$species == "WS"]<-"WhiteStork"
full_data$species[full_data$species == "WhitStork"]<-"WhiteStork"
full_data$species[full_data$species == "Storks-SPEC"]<-"Stork-SPEC"
full_data$species[full_data$species == "WBST"]<-"Stork-SPEC"
full_data$species[full_data$species == "WP"]<-"WhitePelican"
full_data$species[full_data$species == "WhiteP"]<-"WhitePelican"
full_data$species[full_data$species == "Start"]<-"start"
full_data$species[full_data$species == "Start "]<-"start"
full_data$species[full_data$species == "START"]<-"start"
full_data$species[full_data$species == "SHIFT"]<-"shift"
full_data$species[full_data$species == "Shift"]<-"shift"
full_data$species[full_data$species == "END"]<-"end"
full_data$species[full_data$species == "End"]<-"end"
full_data$species[full_data$species == "shot"]<-"SHOT"
full_data$species[full_data$species == "Shot"]<-"SHOT"
full_data$species[full_data$species == "STOP"]<-"end"
full_data$species[full_data$species == "Stop"]<-"end"
full_data$species[full_data$species == "Rain"]<-"rain"
full_data$species[full_data$species == "Comment"]<-"comment"
full_data$species[full_data$species == "Nis"]<-"NIS"
full_data$species[full_data$species == "nis"]<-"NIS"
full_data$species[full_data$species == "Meteo"]<-"meteo"
full_data$age<-tolower(full_data$age)
full_data$age[full_data$age == "adult"]<-"ad"
full_data$age[full_data$age == "Non-Juv"]<-"nonjuv"
full_data$age[full_data$age == "I"]<-"imm"
full_data$age[full_data$age == "A"]<-"ad"
full_data$age[full_data$age == "J"]<-"juv"
full_data$age[full_data$age == "no value"]<-""
full_data$age[full_data$age == "m"]<-""
full_data$age[full_data$age == "fc"]<-""
full_data$age[full_data$age == "f"]<-""
full_data$age[full_data$age == "2cy"]<-"imm"
full_data$age[full_data$age == "2 cy"]<-"imm"
full_data$age[full_data$age == "3cy"]<-"imm"
full_data$age[full_data$age == "3 cy"]<-"imm"
full_data$age[full_data$age == "4cy"]<-"imm"
full_data$age[full_data$age == "4 cy"]<-"imm"
full_data$sex<-tolower(full_data$sex)
full_data$sex[full_data$sex == "no value"]<-""
full_data$sex[full_data$sex == "novalue"]<-""
full_data$sex[full_data$sex == "novalue"]<-""
full_data$sex[full_data$sex == "F"]<-"f"
full_data$sex[full_data$sex == "FC"]<-"fc"
full_data$sex[full_data$sex == "M"]<-"m"
full_data[full_data == "No Value"]<-""
full_data$number[full_data$number == "No Value"]<-0
full_data$number[full_data$number == "NoValue"]<-0
full_data$number[full_data$number == "no value"]<-0
full_data$number[full_data$number == ""]<-0
full_data[full_data =="NoValue"]<-""
full_data<- data.frame(lapply(full_data, function(x) {gsub(";", " ", x)}))
full_data<- data.frame(lapply(full_data, function(x) {gsub(",", " ", x)}))
full_data<- data.frame(lapply(full_data, function(x) {gsub("'", "", x)}))
full_data$countid<-NULL
######################## Converter END ########################

## write data
setwd(outputdir)
write.csv(full_data, "converter_output.csv", fileEncoding ="UTF-8")
